import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "@/components/nav-menu";
import { Toaster } from "@/components/ui/sonner";
import ApolloWrapper from "./provider/apolloprovider";
import ReduxProvider from "./provider/reduxprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
          <ReduxProvider>
          <ApolloWrapper>
          {children}
          </ApolloWrapper>
          </ReduxProvider>

        <Toaster />
      </body>
    </html>
  );
}
